### ISSUE TITLE
수정 요청

### ISSUE THREAD

**Issue by sigmadream** [HYEBing/ks-web#2]
1. 아래 파일의 위치를 옮겨주세요
`src/main/java/controller/IndexController.java` 파일을
`src/main/java/com/hyebin/app/controller/IndexController.java`로 옮겨주세요.

2. 컨트롤러 문법(@Controller 어노테이션)을 적용해주세요

**Comment by HYEBing** [comment]
교수님 확인부탁드립니다.
감사합니다 .

**Comment by sigmadream** [comment]
수고하셨습니다
